name: Boyd Foundation
favicon: null
layout_spectrum: 0.48930567945353687
typography_spectrum: 0.3205952832940966
title: Boyd Foundation | Do Well. Do Good. Do More.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#edebee'
    - '#938266'
    - '#2f3509'
    - '#72581f'
  brandStrength: 0.3210838441736996
  lightness: 0.07837311713956296
  saturation: 0.08394793281331658
  rhythmicContrast: 0.4344940660521388
purpose: []
