name: Boyd Foundation
favicon: null
layout_spectrum: 0.48930567945353687
typography_spectrum: 0.3205952832940966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3210838441736996
  lightness: 0.07837311713956296
  saturation: 0.08394793281331658
  rhythmicContrast: 0.4344940660521388
purpose: []
